services:
  tml:
    container_name: tml
    #restart: unless-stopped
    build:
      context: .
      args:
        UID: 1000
        GID: 1000
        #TML_VERSION: v2023.8.3.3
    #entrypoint: [ "/bin/bash" ] # Uncomment this line if you need to poke around in the container
    tty: true
    stdin_open: true
    ports:
      - 7785:7777
    volumes:
      - ./tModLoader:/home/tml/.local/share/Terraria/tModLoader
    environment:
      - AUTOCREATE=1
      - WORLDNAME=tmlCalamity1.wld
      - DIFFICULTY=1
      # - WORLD=/home/tml/.local/share/Terraria/tModLoader/Worlds/tmlCalamity1.wld
      - PASSWORD=passworld
      - MOTD="Welcome to my tModLoader Server :)"
